version: "3.8"
services:
  server:
    build:
      context: ../
      dockerfile: ./app1/app1.dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    env_file:
      - ../.env
    command:
      - rye
      - run
      - run-app1
